Refactor error types
trussed-dev/littlefs2 pull request #67
Opened 2024-07-03 19:51 UTC by robin-nitrokey

This PR splits the `Error` enum into an `Error` struct and a non-exhaustive `ErrorKind` enum.  This makes it possible to add support for new error codes without breaking compatibility.  The PR also removes the edge case of `Error` instances for non-negative return values indicating success.

See this issue for context and discussion:
- https://github.com/trussed-dev/littlefs2/issues/55

Contrary to the suggestion in https://github.com/trussed-dev/littlefs2/issues/55#issuecomment-2024943423, this implementation does not provide a `fn error(&self) -> Option<ErrorKind>` on `Error`.  It would again cause the problem that users could rely on this method returning `None` for some currently unsupported error.  Instead, `Error` implements `PartialEq<ErrorKind>` so that users can compare it directly against known error kinds.  The only limitation is that it is not possible to `match` on the error kind, but I don’t see a need for that anyway.

2024-07-04 07:36 UTC, sosthene-nitrokey requested changes

2024-07-04 07:36 UTC, sosthene-nitrokey commented on src/io.rs
> +    }
Why here have `N` be a `const generic` ? This can work also with having `N` be a normal argument.

2024-07-04 07:36 UTC, sosthene-nitrokey commented on src/io.rs
> +    const NAMETOOLONG: Self = Self::new_const::<{ ll::lfs_error_LFS_ERR_NAMETOOLONG }>();
I think these could be public

2024-07-04 07:36 UTC, sosthene-nitrokey commented on src/fs.rs
> +                let dir = PathBuf::try_from(&path_slice[..i]).map_err(|_| ErrorKind::Io)?;
Maybe this should be `ErrorKind::NameTooLong`?

2024-07-04 07:51 UTC, robin-nitrokey commented on src/fs.rs
> +                let dir = PathBuf::try_from(&path_slice[..i]).map_err(|_| ErrorKind::Io)?;
I did not want to change the existing behavior, but I think this cannot fail anyway.  If we would have a proper `split` method in `Path`, we could get rid of the error entirely.

2024-07-04 07:53 UTC, robin-nitrokey commented on src/io.rs
> +    }
Right, I missed that when changing the original implementation. Fixed.

2024-07-04 07:53 UTC, robin-nitrokey commented on src/io.rs
> +    const NAMETOOLONG: Self = Self::new_const::<{ ll::lfs_error_LFS_ERR_NAMETOOLONG }>();
Done.

2024-07-04 07:55 UTC, robin-nitrokey commented
If the constants on `Error` are public, we don’t even need the `ErrorKind` enum, do we?

2024-07-04 07:55 UTC, sosthene-nitrokey approved these changes

2024-07-04 08:01 UTC, sosthene-nitrokey commented
That's a good point.

We can re-introduce ErrorKind in the future if we ever need it.

2024-07-04 08:04 UTC, robin-nitrokey commented
Okay.  Then I would change the constant names to match the old variant names, e. g. `NO_SUCH_ENTRY` instead of `NOENT`.

2024-07-16 09:54 UTC, daringer approved these changes

2024-07-18 08:00 UTC, merged